---
name: Websphere
description: Issue with product
labels: tWAS
body:
-  type: "textarea"
   attributes:
     label: "cert issue"
     description: Issue with websphere certificate rotation
   validations:
     required: false
